name: Build and Patch

on:
  workflow_dispatch:
    inputs:
      url:
        description: Download AppImage from URL
        type: string
        required: true

jobs:
  Build-Patch:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt install libcapstone-dev libcapstone3 g++ cmake rapidjson-dev

      - uses: actions/checkout@v2
        with:
          repository: keystone-engine/keystone
          path: keystone
      
      - run: |
          cd keystone
          mkdir build && cd build
          ../make-share.sh
          sudo make install
          sudo ldconfig
          cd ..
      
      - uses: actions/checkout@v2
        with:
          path: navicat-keygen

      - run: |
          cd navicat-keygen
          make all
          wget -O navicat.AppImage ${{ github.event.inputs.url }}
          ls -l navicat.AppImage
          ./scripts/patch.sh navicat
      
      - name: Upload Keygen
        uses: actions/upload-artifact@v2
        with:
          name: navicat-patcher-keygen
          path: bin/
      
      - name: Upload AppImage
        uses: actions/upload-artifact@v2
        with:
          name: navicat-patched
          path: navicat-patched.AppImage
